### PR TITLE
Handle multiple non-radio inputs with same name

### PR DESCRIPTION
**Pull request by jnothman**

### CODE REVIEW

**Comment by jnothman** [comment]
I might give some motivation: say you want to input a multi-valued field where the order matters. Yes, you could number each field, but `?key=value1&key=value2&key=value3` is sufficient representation. And `form.serialize()` will gladly return this for `<input name=key value=value1><input name=key value=value2><input name=key value=value3>`. This helps unserialise that case, by allowing any input name to be duplicated and restoring the values in order of appearance in the serialized form.

**Comment by cthielen** [comment]
This appears to work fine on Chrome and Firefox but the three "Best Friends" inputs do not work on the latest version of Safari. Any ideas?

**Comment by jnothman** [comment]
I had problems with Safari refusing to use localStorage due to security policies. Once I changed it to use a global variable, saving and loading both worked fine.

**Comment by jnothman** [comment]
`@@ -102,7 +102,7 @@

diff --git a/test.html b/test.html
index 2e66b0f..bb71105 100644
--- a/test.html
+++ b/test.html
@@ -102,7 +102,7 @@
   <script type="text/javascript">
     function test_save() {
       var s = $("form#test").serialize(); // save form settings.
-      localStorage.setItem('the_form', s); // save in HTML5 session storage
+      the_form = s // localStorage.setItem('the_form', s); // save in HTML5 session storage
     }

        function test_clear() {
@@ -117,7 +117,7 @@

     // The actual jQuery.unserializeForm test
     function test_load() {
-      var s = localStorage.getItem('the_form');
+      var s = the_form; // localStorage.getItem('the_form');
       $("form#test").unserializeForm(s);
     }
   </script>
```

**Comment by cthielen** [comment]
Ah, gotcha. Looks good, thanks!

**Pull request merged**
